version: '2'
services:
  wazo:
    build:
      context: ${OS}
      args:
        - FQDN=${FQDN}
        - HOSTNAME=${HOSTNAME}
    environment:
      - PASSWD=${PASSWD}
    dns:
      - ${DNS1}
      - ${DNS2}
    ports:
     - "69:69/udp"
     - "14080:80"
     - "14443:443"
     - "2000:2000"
     - "4573:4573"
     - "5003:5003"
     - "5004:5004"
     - "5038:5038"
     - "5060:5060/udp"
     - "5432:5432"
     - "5672:5672"
     - "8666:8666"
     - "8667:8667"
     - "8668:8668"
     - "8669:8669"
     - "9486:9486"
     - "9489:9489"
     - "9495:9495"
cap_add:
  - SYS_ADMIN
