.catalog:
  name: "WAZO"
  version: "v0.1"
  description: "WAZO Server"
  uuid: wazo-0
  questions:
    - variable: "PASSWD"
      label: "Password"
      description: "Root password"
      type: "password"
      required: true
    - variable: "OS"
      label: "Operating System"
      description: "Supported Operating System Debian 7"
      required: true
      type: "enum"
      options:
        - "https://raw.githubusercontent.com/cutech/docker-wazo/Dockerfile"
      default: "https://raw.githubusercontent.com/cutech/docker-wazo/Dockerfile"
    - variable: "DNS1"
      label: "Extra DNS1"
      description: "DNS1 in addition to host server"
      type: "string"
      required: false
      default: "127.0.0.1"
    - variable: "DNS2"
      label: "Extra DNS2"
      description: "DNS2 in addition to host server"
      type: "string"
      required: false
      default: "8.8.8.8"
    - variable: "SSH"
      label: "SSH external port"
      description: "RancherOS is hardcoded at 22"
      type: "string"
      required: true
      default: "14022"
    - variable: "HOSTNAME"
      label: "Hostname"
      description: "Server hostname"
      type: "string"
      required: true
    - variable: "FQDN"
      label: "FQDN"
      description: "Fully qualified domain name"
      required: true
      type: "string"
    - variable: "DATA_VOLUME"
      label: "Data Volume"
      description: "Host directory or Convoy volume name, followed by a colon (':'). E.g.: '/rancher/wazo/home:'; 'wazo-data:'"
      type: "string"
      default: "/rancher/wazo/home:"
    - variable: "VOLUME_DRIVER"
      description: "Name of Convoy Storage Pool, if one is used."
      type: "string"
