name: Minecraft
description: |
  Mojang's voxel based world creation environment
version: v1.12.2
category: entertainment
maintainer: cutech <cody@c-u-tech.com>
license: GNU General Public License v2.0
projectURL: https://github.com/cutech/rOS-catalog/templates/minecraft
