.catalog:
  name: "Minecraft"
  version: "v1.11.1"
  description: "Minecraft server"
  uuid: minecraft-0
  questions:
    - variable: "EULA"
      label: "Accept EULA"
      description: "Select TRUE to accept the Minecraft EULA"
      required: true
      type: "enum"
      options:
        - TRUE
      default: true
    - variable: "ENABLE_QUERY"
      label: "Query enable"
      description: "Enable Minecraft query port"
      default: true
      required: false
      type: "boolean"
    - variable: "QUERY_PORT"
      label: "Query port number"
      description: "On which port (UDP, default 25565) should the query protocol bind?"
      default: 25565
      required: false
      type: "int"
    - variable: "VERSION"
      label: "Minecraft Version"
      description: "Select the version of Minecraft server to run. Default is the latest available."
      type: "enum"
      default: LATEST
      options:
        - LATEST
        - SNAPSHOT
        - 1.11
        - 1.8.9
        - 1.7.10
        - 1.6.4
    - variable: "DIFFICULTY"
      label: "Difficulty level"
      description: "Select the Minecraft difficulty level.  Default is normal"
      default: normal
      required: true
      type: "enum"
      options:
        - peaceful
        - easy
        - normal
        - hard
    - variable: "MODE"
      label: "Default game mode"
      description: "Select the game mode to connect in.  Default is survival"
      default: survival
      required: true
      type: "enum"
      options:
        - survival
        - creative
        - adventure
        - spectator
    - variable: "LEVEL_TYPE"
      label: "Level Type"
      description: ""
      default: "DEFAULT"
      type: "enum"
      options:
        - DEFAULT
        - FLAT
        - LARGEBIOMES
        - AMPLIFIED
        - CUSTOMIZED
    - variable: "GENERATOR_SETTINGS"
      label: "Generator Settings"
      description: "Custom generator settings. Only used for level types FLAT and CUSTOMIZED."
      type: "string"
    - variable: "PVP"
      label: "PvP mode"
      description: "Check here to enable PvP mode.  Default is no PvP."
      default: false
      type: "boolean"
      required: true
    - variable: "MOTD"
      label: "Description"
      description: "Description string for Minecraft server"
      default: "A Minecraft server powered by Docker"
      type: "string"
      required: true
    - variable: "WHITELIST"
      label: "Whitelist"
      description: "Player names to whitelist, comma separated"
      type: "string"
    - variable: "OPS"
      label: "Operators"
      description: "Player names to give operator privileges, comma separated"
      type: "string"
    - variable: "SEED"
      label: "Level seed"
      description: "Optional level seed number for world generation"
      type: "int"
    - variable: "WORLD"
      label: "World URL"
      description: "URL to download zipped world directory"
      type: "string"
    - variable: "DATA_VOLUME"
      label: "Data Volume"
      description: "Host directory or Convoy volume name, followed by a colon (':'). E.g.: '/mnt/data:'; 'minecraft-data:'"
      type: "string"
    - variable: "VOLUME_DRIVER"
      description: "Name of Convoy Storage Pool, if one is used."
      type: "string"
    - variable: "ICON"
      label: "Icon URL"
      description: "URL to download server icon, for 64x64 pixel png target"
      type: "string"
    - variable: "INIT_MEMORY"
      label: "JVM -Xms"
      description: "JVM memory heap size initial allocation in [g|G|m|M|k|K]"
      default: 512M
      required: false
      type: "string"
    - variable: "MAX_MEMORY"
      label: "JVM -Xmx"
      description: "JVM memory heap size maximum allocation in [g|G|m|M|k|K]"
      default: 1G
      required: false
      type: "string"
    - variable: "MAX_PLAYERS"
      label: "Max players"
      description: "Maximum number of players"
      default: 20
      required: true
      type: "int"
    - variable: "MAX_TICK_TIME"
      label: "Max tick"
      description: "The maximum number of milliseconds a single tick may take before the server watchdog stops the server"
      default: 60000
      required: false
      type: "int"
    - variable: "VIEW_DISTANCE"
      label: "View Distance"
      description: "Sets the server-side viewing radius, measured in chunks"
      default: 10
      required: false
      type: "int"
    - variable: "TYPE"
      label: "Mod Type"
      description: "Forge, Bukkit, Spigot, Paper, Feed-The-Beast (All default to latest version)"
      required: false
      type: "enum"
      options:
        - FORGE
        - BUKKIT
        - SPIGOT
        - PAPER
        - FTB
