.catalog:
  name: "Virtualmin"
  version: "v0.1"
  description: "Virtualmin server"
  uuid: virtualmin-0
  questions:
    - variable: "UNINSTALL"
      label: "Uninstall"
      description: "Removes all Virtualmin packages (do not use on a production system)"
      required: false
      type: "enum"
      options:
        - "-u"
      default: ""
    - variable: "HOSTNAME"
      label: "Hostname"
      description: "Server hostname"
      type: "string"
      required: true
    - variable: "FQDN"
      label: "FQDN"
      description: "Fully qualified domain name"
      required: true
      type: "string"
    - variable: "SETUP"
      label: "Setup"
      description: "Setup software repositories and exit (no installation or configuration)"
      required: false
      type: "enum"
      options:
        - "-s"
      default: ""
    - variable: "MINIMAL"
      label: "Minimal"
      description: "Install a smaller subset of packages for low-memory/low-resource systems"
      required: false
      type: "enum"
      options:
        - "-m"
      default: ""
    - variable: "BUNDLE"
      label: "Bundle"
      description: "Choose bundle to install (LAMP or LEMP, defaults to LAMP)"
      required: false
      type: "enum"
      options:
        - "-b LAMP"
        - "-b LEMP"
      default: ""
    - variable: "DISABLE"
      label: "Disable"
      description: "Disable feature [SCL|EPEL|PG]"
      required: false
      type: "enum"
      options:
        - "--disable SCL"
        - "--disable EPEL"
        - "--disable PG"
      default: ""
