.catalog:
  name: "Virtualmin"
  version: "v0.1"
  description: "Virtualmin server"
  uuid: virtualmin-0
  questions:
    - variable: "OS"
      label: "Operating System"
      description: "Supported Operating Systems; CentOS/RHEL Linux 6 and 7 on x86_64 | Debian 7, 8, and 9, on i386 and amd64 | Ubuntu 14.04 LTS and 16.04 LTS, on i386 and amd64"
      required: true
      type: "enum"
      options:
        - "centos:latest"
        - "centos:7"
        - "centos:7.4.1708 "
        - "centos:7.3.1611"
        - "centos:7.2.1511"
        - "centos:7.1.1503"
        - "centos:7.0.1406"
        - "centos:6"
        - "centos:6.9"
        - "centos:6.8"
        - "centos:6.7"
        - "centos:6.6"
        - "debian:stretch"
        - "debian:stretch-backports"
        - "debian:stretch-slim"
        - "debian:jessie"
        - "debian:jessie-backports"
        - "debian:jessie-slim"
        - "debian:wheezy"
        - "debian:wheezy-backports"
        - "debian:wheezy-slim"
        - "ubuntu:16.04"
        - "ubuntu:14.04"
      default: ""
