.catalog:
  name: "Odoo"
  version: v0.2
  description: "Odoo ERP"
  uuid: odoo-0
  questions:
    - variable: "ODOO_VERSION"
      label: "Odoo Version"
      description: "Odoo Version 9.0, 10.0, 11.0, Latest (11.0)"
      required: true
      type: "enum"
      options:
        - 9.0
        - 10.0
        - 11.0
        - latest
      default: "11.0"
    - variable: "ODOO_RELEASE"
      label: "Odoo Release"
      description: "Odoo release version latest or date YYYYMMDD e.g. 20171107"
      required: true
      type: "string"
      default: "latest"
    - variable: XXPORT
      description: "Odoo UI (xmlrpc) port; External"
      label: "Ext. Odoo Port"
      required: true
      default: "8069"
      type: "int"
    - variable: "IXPORT"
      description: "Odoo UI (xmlrpc) port; Internal"
      label: "Int. Odoo Port"
      required: true
      default: "8069"
      type: "int"
    - variable: "XXSPORT"
      description: "Odoo Secure (xmlrpcs) port; External"
      label: "Odoo Secure Port"
      required: true
      default: "8071"
      type: "int"
    - variable: "IXSPORT"
      description: "Odoo Secure (xmlrpcs) port; Internal"
      label: "Odoo Secure Port"
      required: true
      default: "8071"
      type: "int"
    - variable: "XLPPORT"
      description: "Odoo Longpolling port; External"
      label: "Longpoll Port"
      required: true
      default: "8072"
      type: "int"
    - variable: "ILPPORT"
      description: "Odoo Longpolling port; Internal"
      label: "Longpoll Port"
      required: true
      default: "8072"
      type: "int"
    - variable: "ODOO_CONF_FILE"
      label: "Config File"
      description: "Odoo COnfig file name e.g. odoo.conf"
      required: true
      default: "odoo.conf"
      type: "string"
    - variable: "ADDONS_PATH"
      label: "Odoo addons"
      description: "Odoo addons path e.g. /mnt/extra-addons"
      required: true
      default: "; addons_path = /mnt/extra-addons"
      type: "string"
    - variable: "ODOO_DATA_DIR"
      label: "Odoo Data"
      description: "Odoo data directory e.g. /var/lib/odoo"
      required: true
      default: "; data_dir = /var/lib/odoo"
      type: "string"
    - variable: "ADMIN_PASSWORD"
      label: "Admin Password"
      description: "Odoo admin password"
      required: true
      default: "admin"
      type: "password"
    - variable: "CSV_SEP"
      label: "CSV Seperator"
      description: "Comma seperated value file, internal seperator e.g. ,"
      required: true
      default: "; csv_internal_sep = ,"
      type: "string"
    - variable: "DB_MAXCONN"
      label: "DB Max Connections"
      description: "Maximum number of concurrent database connections e.g 64"
      required: true
      default: "; db_maxconn = 64"
      type: "string"
    - variable: "DB_NAME"
      label: "DB Name"
      description: "Name of database to pre-load e.g. odoo"
      required: true
      default: "; db_name = False"
      type: "string"
    - variable: "DB_TEMPLATE"
      label: "DB Template"
      description: "Database default template e.g. template1"
      required: true
      default: "; db_template = template1"
      type: "string"
    - variable: "DB_FILTER"
      label: "DB Filter"
      description: "Databse subdomain filter for multiple accounts e.g. ^%d$"
      required: true
      default: "; dbfilter = .*"
      type: "string"
    - variable: "DEBUG_MODE"
      label: "Debug Mode"
      description: "Start Odoo with the Developer Mode set to on"
      required: true
      default: "; debug_mode = False"
      type: "string"
    - variable: "EMAIL_FROM"
      label: "Email From"
      description: "Specify the SMTP email address for sending email"
      required: true
      default: "; email_from = False"
      type: "string"
    - variable: "MEM_LIMIT_H"
      label: "Memory Limit Hard"
      description: "Maximum allowed virtual memory, in bytes, per worker, when reached, any memory allocation will fail e.g. 805306368 = 768MiB"
      required: true
      default: "; limit_memory_hard = 805306368"
      type: "string"
    - variable: "MEM_LIMIT_S"
      label: "Memory Limit Soft"
      description: "Maximum allowed virtual memory, in bytes, per worker, when reached the worker be reset after the current request e.g. 671088640 = 640MiB"
      required: true
      default: "; limit_memory_soft = 671088640"
      type: "string"
    - variable: "LIMIT_REQ"
      label: "Limit Requests"
      description: "Maximum number of requests to be processed per worker"
      required: true
      default: "; limit_request = 8192"
      type: "string"
    - variable: "LIMIT_TIME_CPU"
      label: "CPU Time Limit"
      description: "Maximum allowed CPU time, in seconds, per request"
      required: true
      default: "; limit_time_cpu = 60"
      type: "string"
    - variable: "LIMIT_TIME_REAL"
      label: "Real Time Limit"
      description: "Maximum allowed Real time, in seconds, per request"
      required: true
      default: "; limit_time_real = 120"
      type: "string"
    - variable: "LIST_DB"
      label: "List DB"
      description: "List databases, when set to false Odoo will not return a list of the databases available"
      options:
        - True
        - False
      default: "true"
      type: "enum"
    - variable: "LOG_DB"
      label: "Log DB"
      description: "If True, writes log to the ‘ir_logging’ table in the database"
      required: true
      default: "; log_db = False"
      type: "string"
    - variable: "LOG_HANDLER"
      label: "Log Handler"
      description: "Fomat is a list of ‘module:log_level’ pairs. The default value is ‘:INFO’ – it means the default logging level is ‘INFO’ for all modules, e.g. openerp.addons.my_addon1:DEBUG,openerp.addons.my_addon2:DEBUG"
      required: true
      default: "; log_handler = [':INFO']"
      type: "string"
    - variable: "LOG_LEVEL"
      label: "Log Level"
      description: "One of the following levels 'info', 'warn', 'error', 'critical', 'debug', 'debug_sql', 'debug_rpc_answer', 'debug_rpc'"
      required: true
      options:
        - info
        - warn
        - error
        - critical
        - debug
        - debug_sql
        - debug_rpc
        - debug_rpc_answer
      default: "info"
      type: "enum"
    - variable: "LOGFILE"
      label: "Logfile"
      description: "Log filename e.g. /var/log/odoo/error.log. If none, it defaults to stdout (terminal)"
      required: true
      default: "; logfile = None"
      type: "string"
    - variable: "CHRON_THREADS"
      label: "Max Chron Threads"
      description: "Number of workers dedicated to cron jobs. Defaults to 2. The workers are threads in multithreading mode and processes in multiprocessing mode."
      required: true
      default: "; max_cron_threads = 2"
      type: "string"
    - variable: "OSV_MEM_AGE"
      label: "OSV Memory Age"
      description: "Maximum age, in hours, of records kept in the virtual osv_memory tables"
      required: true
      default: "; osv_memory_age_limit = 1.0"
      type: "string"
    - variable: "OSV_MEM_COUNT"
      label: "OSV Memory Count"
      description: "Maximum number of records kept in the virtual osv_memory tables"
      required: true
      default: "; osv_memory_count_limit = False"
      type: "string"
    - variable: "PROXY_MODE"
      label: "Proxy Mode"
      description: "Set to true when behind a HTTPS/SSL reverse proxy"
      required: true
      default: "; proxy_mode = False"
      type: "string"
    - variable: "SMTP_PASSWORD"
      label: "SMTP Password"
      description: "Specify the SMTP password for sending email"
      required: true
      default: "; smtp_password = False"
      type: "string"
    - variable: "SMTP_PORT"
      label: "SMTP Port"
      description: "Specify the SMTP port"
      required: true
      default: "; smtp_port = 25"
      type: "string"
    - variable: "SMTP_SERVER"
      label: "SMTP_Server"
      description: "Specify the SMTP server for sending email"
      required: true
      default: "; smtp_server = localhost"
      type: "string"
    - variable: "SMTP_SSL"
      label: "SMTP SSL"
      description: "If passed, SMTP connections will be encrypted with SSL e.g. STARTTLS"
      required: true
      default: "; smtp_ssl = False"
      type: "string"
    - variable: "SMTP_USER"
      label: "SMTP User"
      description: "Specify the SMTP username for sending email"
      required: true
      default: "; smtp_user = False"
      type: "string"
    - variable: "WORKERS"
      label: "Workers"
      description: "Specify the number of workers, 0 disable prefork mode. Worker number calculation rule of thumb; (#CPU * 2) + 1, Cron workers need CPU, 1 worker ~= 6 concurrent users"
      required: true
      default: "; workers = 0"
      type: "string"
    - variable: "XMLRPC"
      label: "XMLRPC"
      description: "If false, do not start the HTTP or long-polling workers (may still start cron workers), has no effect if --test-enable is set, as tests require an accessible HTTP server"
      required: true
      default: "; xmlrpc = True"
      type: "string"
    - variable: "XMLRPC_IP"
      label: "XMLRPC Interface"
      description: "TCP/IP address on which the HTTP server listens, defaults to 0.0.0.0 (all addresses)"
      required: true
      default: "; xmlrpc_interface = "
      type: "string"
    - variable: "XMLRPC_PORT"
      label: "XMLRPC Port"
      description: "Port on which the HTTP server listens, defaults to 8069"
      required: true
      default: "; xmlrpc_port = 8069"
      type: "string"
    - variable: "XMLRPCS"
      label: "XMLRPCS"
      description: "DEPRECIATED use reverse proxy"
      required: true
      default: "; xmlrpcs = True"
      type: "string"
    - variable: "XMLRPCS_IP"
      label: "XMLRPCS Interface"
      description: "DEPRECIATED use reverse proxy"
      required: true
      default: "; xmlrpcs_interface = "
      type: "string"
    - variable: "XMLRPCS_PORT"
      label: "XMLRPCS Port"
      description: "DEPRECIATED use reverse proxy"
      required: true
      default: "; xmlrpcs_port = 8071"
      type: "string"
    - variable: "ODOO_CONFIG_VOL"
      label: "odoo.conf"
      description: "Host directory or Convoy volume name for /etc/odoo/odoo.conf, followed by a colon (':'). E.g.: '/odoo/config:'; 'odoo-config:'"
      type: "string"
    - variable: "ODOO_ADDONS-VOL"
      label: "addons"
      description: "Host directory or Convoy volume name for /usr/lib/python3/dist-packages/odoo/addons, followed by a colon (':'). E.g.: '/odoo/addons:'; 'odoo-addons:'"
      type: "string"
    - variable: "ODOO_WEB_DATA_VOL"
      label: "Odoo web data (/var/lib/odoo)"
      description: "Host directory or Convoy volume name for /var/lib/odoo, followed by a colon (':'). E.g.: '/odoo/webdata:'; 'odoo-config:'"
      type: "string"
    - variable: PGUSER
      description: "Postgres username"
      label: "Postgres username"
      required: true
      default: "odoo"
      type: "string"
    - variable: PGPASS
      description: "Database password"
      label: "DB password"
      required: true
      default: "password"
      type: "password"
